[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install',
  'npx prisma generate'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx prisma migrate deploy && npm run start:prod'
