# Render.com Blueprint File
services:
  - type: web
    name: expenses-app-backend
    runtime: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
